name: Systemd images

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          centos-7:
            - centos-7/Dockerfile
          centos-8:
            - centos-8/Dockerfile
          debian-9:
            - debian-9/Dockerfile
          debian-10:
            - debian-10/Dockerfile
          fedora-30:
            - fedora-30/Dockerfile
          ubuntu-16.04:
            - ubuntu-16.04/Dockerfile
          ubuntu-18.04:
            - ubuntu-18.04/Dockerfile
  test:
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout postgres exporter
        uses: actions/checkout@v2
        with:
          repository: zhan9san/ansible-postgres-exporter
          path: './ansible-postgres-exporter'

      - name: Build ${{ matrix.package }}
        run: docker build -t zhan9san/systemd:${{ matrix.package }} .
        working-directory: ${{ matrix.package }}

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible

      - name: Install test dependencies.
        run: pip install -r test-requirements.txt
        working-directory: 'ansible-postgres-exporter'

      - name: Run Molecule tests.
        run: molecule test
        working-directory: 'ansible-postgres-exporter'

  push_to_registries:
    needs:
      - changes
      - test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.package }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:${{ matrix.package }}
